"""Import BEO 6.21-8.30 Report into FIN graph"""
import json, re, shutil, sys
sys.stdout.reconfigure(encoding="utf-8")
from pathlib import Path
from collections import Counter

FIN_GRAPH = Path(r"C:\Users\Y\.openclaw\workspace\knowledge_center\fin_graph.json")

RAW_TEXT = """SZVTV Daily Event-BQ Generated By: Elaine He HM AP 1 21/06/2026 10:04 Filtered By: Show: All booking events Date Field: Event Start Date equals Custom (21/06/2026 to 31/08/2026) Event Status equals Definite,Prospect,Tentative Sorted By: Event Start Date: Event Start Date - Sorted ascending Booking Post As: Alternate Booking Booking Post As: Booking Post As: Start Time 24 End Time 24 Function Room Booking Event: Event Function Room Setup Expecte Guarante Set BEO Event Booking Post As: Owner Booking Post As: Service Booking Post As: Catering
Event Start Date: 21/06/2026 (2 records)
杜老师孙儿周岁午宴 Mrs.Du's grandson ceremony lunch 11:30 14:30 Function Room 3+4 Lunch Round Tables of 10 20 20 20 Mrs.Du's grandson ceremony lunch: 7721-BEO Definite Luisa Liu Luisa Liu Luisa Liu
杜老师孙儿周岁午宴 Mrs.Du's grandson ceremony lunch 7:00 11:00 Function Room 3+4 Setup Round Tables of 10 2 2 2 Mrs.Du's grandson ceremony lunch: 7721-BEO Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 22/06/2026 (2 records)
香港中文大学招生讲座 The Chinese University Of HongKong Meeting 18:00 23:00 Grand Ballroom 3 Meeting Theater 208 208 ## The Chinese University Of HongKong Meeting: 7722-BEO Definite Luisa Liu Luisa Liu Luisa Liu
香港中文大学招生讲座 The Chinese University Of HongKong Meeting 13:00 22:00 VIP Room Meeting Existing Setup 15 15 15 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 23/06/2026 (1 record)
平安银行晚餐�?Ping An Bank Meeting Dinner 14:00 21:00 Function Room 6 Dinner Round Tables of 10 30 30 30 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 24/06/2026 (1 record)
南通如东住建局 Nantong Zhu Jian Ju 18:00 21:15 All Day Dining OPEN Dinner Buffet Existing Setup 70 60 70 - Definite Cecily Hong Luisa Liu Luisa Liu
Event Start Date: 25/06/2026 (3 records)
南通如东住建局 Nantong Zhu Jian Ju 11:00 13:00 Function Room 1 Lunch Round Tables of 10 70 70 70 - Definite Cecily Hong Luisa Liu Luisa Liu
西门子会�?Simens Suzhou Branch Meeting 12:00 17:00 Function Room 3+4 Meeting Classroom 60 60 60 - Tentative Lily Xie - -
西门子会�?Simens Suzhou Branch Meeting 17:00 20:00 Function Room 1 Dinner Round Tables of 10 50 50 50 - Tentative Lily Xie - -
Event Start Date: 26/06/2026 (5 records)
合合信息闭门会议 SH Hehe Information meeting 8:00 17:30 Function Room 1 Meeting Fish Bone 50 50 50 - Tentative Nico Lin - -
合合信息闭门会议 SH Hehe Information meeting 15:00 15:30 Coffee Break Area Break PM Coffee Station 20 20 20 - Tentative Nico Lin - -
合合信息闭门会议 SH Hehe Information meeting 10:00 10:30 Coffee Break Area Break AM Coffee Station 20 20 20 - Tentative Nico Lin - -
江苏省招标中心会�?Jiangsu Bidding Center Meeting 8:00 18:00 Function Room 3+4 Meeting Hollow Square 40 40 40 - Tentative Luisa Liu Luisa Liu Luisa Liu
硕腾会议 Zoetis Suzhou Manufacuring Co Ltd 8:00 18:00 Function Room 6 Meeting Special Setup 40 40 40 - Prospect Elaine He - -
Event Start Date: 27/06/2026 (5 records)
广州康普基金�?MSD活动 Guangzhou Pukang Meeting 12:00 17:00 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Lily Xie - -
数智医学研究中心会议 Digital Intelligence Medical Research Center 8:00 18:00 Grand Ballroom 2+3 Meeting Existing Setup 80 70 80 - Tentative Cecily Hong - -
朴女士家的宝宝宴 The lunch of Ms. piao 11:00 14:00 Grand Ballroom 1 Lunch Round Tables of 10 80 80 80 - Definite Nico Lin - -
朴女士家的宝宝宴 The lunch of Ms. piao 12:00 14:00 VIP Room Room Hold Existing Setup 5 5 5 - Definite Nico Lin - -
朴女士家的宝宝宴 The lunch of Ms. piao 8:00 11:00 Grand Ballroom 1 Setup Existing Setup 5 5 5 - Definite Nico Lin - -
Event Start Date: 28/06/2026 (3 records)
上海歆�?MSD SHA Xinsi-MSD Group 8:30 17:30 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Catherine Xu - -
苏智协掼蛋比赛和晚宴 suzhixie meeting&dinner 13:00 17:30 Function Room 1 Meeting Existing Setup 40 40 40 - Prospect Nico Lin - -
苏智协掼蛋比赛和晚宴 suzhixie meeting&dinner 17:30 21:00 Function Room 1 Dinner Round Tables of 10 30 30 30 - Prospect Nico Lin - -
Event Start Date: 01/07/2026 (3 records)
研华科技活动 Beijing Advantech Xingye Electronic Technology 10:00 18:00 VIP Room Meeting Existing Setup 8 6 8 - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 7:00 18:00 Grand Ballroom Meeting Classroom 500 500 ## - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 10:00 18:00 Business Center Meeting Room Hold Existing Setup 8 6 8 - Definite Elaine He - -
Event Start Date: 02/07/2026 (8 records)
上海赛福化工会议 Shanghai Sai Fu meeting 8:30 17:30 Function Room 1 Meeting Classroom 70 70 70 - Prospect Nico Lin - Elaine He
上海赛福化工会议 Shanghai Sai Fu meeting 11:00 14:00 Function Room 5+6 New Event Classroom 60 60 60 - Prospect Nico Lin - Elaine He
研华科技活动 Beijing Advantech Xingye Electronic Technology 13:30 18:00 Function Room 2+3+4 Meeting Classroom 30 20 30 - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 12:00 13:00 Bar Beer Society Lunch Buffet Existing Setup 100 100 ## - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 12:00 13:00 Italian Resterant BACIO Lunch Buffet Existing Setup 80 80 80 - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 12:00 13:00 All Day Dining OPEN Lunch Buffet Existing Setup 150 150 ## - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 8:30 18:00 Grand Ballroom Foyer Break Coffee Station 200 200 ## - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 15:00 15:30 Grand Ballroom Foyer Break PM Coffee Station 250 250 ## - Definite Elaine He - -
Event Start Date: 03/07/2026 (2 records)
中科看点活动 Zhongke Kandian Meeting 12:00 17:30 Grand Ballroom 3 Meeting Classroom 105 105 ## - Definite Nico Lin - -
中科看点活动 Zhongke Kandian Meeting 11:00 17:30 Rest Room/Bride Room Setup Existing Setup 10 10 10 - Definite Nico Lin - -
Event Start Date: 04/07/2026 (4 records)
上海同济大学活动 SHA Tong Ji Universiy Group 13:00 18:30 Function Room 1 Meeting Classroom 50 50 50 - Definite Cecily Hong - Nico Lin
上海同济大学活动 SHA Tong Ji Universiy Group 15:00 15:30 Coffee Break Area Break PM Coffee Station 20 20 20 - Definite Cecily Hong - Nico Lin
罗氏会议 Roche meeting 8:30 12:00 Function Room 6 Meeting U Shape 40 40 40 - Tentative Cecily Hong - Nico Lin
罗氏会议 Roche meeting 10:00 10:30 Function Room Foyer Break AM Coffee Station 15 15 15 - Tentative Cecily Hong - Nico Lin
Event Start Date: 05/07/2026 (3 records)
恩德斯豪斯公司晚�?Endress Hauser Dinner 15:00 21:00 Function Room 2+3+4 Dinner Round Tables of 10 80 70 80 - Prospect Luisa Liu Luisa Liu Luisa Liu
苏州音为梦组织钢琴比�?Suzhou Yinfeng Dream Art Piano competition 7:00 17:30 Function Room 1 Meeting Theater 80 80 80 - Prospect Nico Lin - -
苏州音为梦组织钢琴比�?Suzhou Yinfeng Dream Art Piano competition 18:00 21:00 Function Room 6 Dinner Round Tables of 10 20 20 20 - Prospect Nico Lin - -
Event Start Date: 08/07/2026 (1 record)
壹枝文化-华为会议 Yizhi Culture-huawei meeting 8:00 23:45 Grand Ballroom 1+2 Setup Existing Setup 10 10 10 - Prospect Nico Lin - -
Event Start Date: 09/07/2026 (3 records)
壹枝文化-华为会议 Yizhi Culture-huawei meeting 11:00 17:30 TBA Meeting Classroom 150 150 ## - Prospect Nico Lin - -
泸州老窖活动 Luzhou Laojiao Group 8:30 17:30 Grand Ballroom 3 Meeting Classroom 100 100 ## - Prospect Catherine Xu - -
泸州老窖活动 Luzhou Laojiao Group 17:00 21:30 Grand Ballroom 2 Dinner Oval Tables of 10 120 120 ## - Prospect Catherine Xu - -
Event Start Date: 10/07/2026 (2 records)
上海芯源活动 SHA Xinyu Systems 16:00 21:00 Grand Ballroom 2+3 Dinner Oval Tables of 10 180 180 ## - Prospect Catherine Xu - -
泸州老窖活动 Luzhou Laojiao Group 8:30 17:30 Grand Ballroom 1 Meeting Classroom 100 100 ## - Prospect Catherine Xu - -
Event Start Date: 12/07/2026 (3 records)
上海维度--IT SHA WeiDu--IT 8:00 22:00 Grand Ballroom 2+3 Meeting Existing Setup 250 230 ## - Prospect Cecily Hong - -
陈先生家升学�?Thanks Dinner of Mr.Chen 15:00 21:00 Grand Ballroom 1 Dinner Round Tables of 10 70 70 70 - Prospect Luisa Liu Luisa Liu Luisa Liu
陈先生家升学�?Thanks Dinner of Mr.Chen 13:00 21:00 VIP Room Room Hold Existing Setup 20 20 20 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 13/07/2026 (1 record)
上海维度--IT SHA WeiDu--IT 8:00 18:00 Grand Ballroom Meeting Existing Setup 250 230 ## - Prospect Cecily Hong - -
Event Start Date: 17/07/2026 (2 records)
深圳越疆机器人展示会�?SZ yuejiang meeting 9:00 18:00 Grand Ballroom 2+3 Meeting Classroom 180 180 ## - Prospect Nico Lin - -
赛默飞会�?Thermo Fisher Meeting 7:00 18:00 Function Room 3+4 Meeting Classroom 63 63 63 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 18/07/2026 (4 records)
李先生订婚午�?Mr.Li's Engagement Lunch 7:00 15:00 Grand Ballroom 1 Lunch Round Tables of 10 100 90 ## - Definite Luisa Liu Nico Lin Nico Lin
渣打银行会议 Standard Chartered Bank Meeting 7:00 17:00 Grand Ballroom 3 Meeting Classroom 72 63 63 - Definite Luisa Liu Luisa Liu Luisa Liu
渣打银行会议 Standard Chartered Bank Meeting 15:00 15:30 Grand Ballroom Foyer Break PM Coffee Station 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
渣打银行会议 Standard Chartered Bank Meeting 7:00 11:00 Grand Ballroom 3 Setup Classroom 2 2 2 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 19/07/2026 (3 records)
沈书记家的宝宝宴 The Baby Lunch of Mr. Shen 8:00 14:00 Grand Ballroom 1+2 Lunch Round Tables of 10 180 180 ## - Definite Elaine He - -
沈书记家的宝宝宴 The Baby Lunch of Mr. Shen 8:00 14:00 VIP Room Room Hold Existing Setup 15 12 15 - Definite Elaine He - -
沈书记家的宝宝宴 The Baby Lunch of Mr. Shen 8:00 14:00 Rest Room/Bride Room Room Hold No Set Up Required 8 6 8 - Definite Elaine He - -
Event Start Date: 22/07/2026 (5 records)
中科看点活动 Zhongke Kandian Meeting 12:00 17:30 Grand Ballroom 3 Meeting Classroom 105 105 ## - Prospect Nico Lin - -
中科看点活动 Zhongke Kandian Meeting 11:00 17:30 Rest Room/Bride Room Setup Existing Setup 10 10 10 - Prospect Nico Lin - -
建筑技艺杂�?Jian Zhu Yi Ji 13:00 21:00 Function Room 1 Dinner Round Tables of 10 40 40 40 - Prospect Cecily Hong - -
海德声科会议 HEAD Meeting 9:00 18:00 Function Room 4 Meeting Classroom 40 40 40 - Prospect Lily Xie - -
海德声科会议 HEAD Meeting 9:00 18:00 Function Room 6 Meeting Classroom 40 40 40 - Prospect Lily Xie - -
Event Start Date: 23/07/2026 (3 records)
建筑技艺杂�?Jian Zhu Yi Ji 8:00 19:00 Grand Ballroom 2+3 Meeting Existing Setup 200 180 ## - Prospect Cecily Hong - -
海德声科会议 HEAD Meeting 9:00 18:00 Function Room 4 Meeting Classroom 40 40 40 - Prospect Lily Xie - -
苏州同元软控活动 SZ Tongyuan Software Group 8:30 17:30 Grand Ballroom 1 Meeting Classroom 500 500 ## - Prospect Catherine Xu - -
Event Start Date: 24/07/2026 (2 records)
上海华源磁业活动 SHA Huayuan Ci Ye Group 8:30 17:30 Grand Ballroom 2+3 Meeting Classroom 100 100 ## - Prospect Catherine Xu - -
苏州同元软控活动 SZ Tongyuan Software Group 8:30 17:30 Grand Ballroom 1 Meeting Classroom 100 100 ## - Prospect Catherine Xu - -
Event Start Date: 25/07/2026 (2 records)
上海华源磁业活动 SHA Huayuan Ci Ye Group 8:30 17:30 Grand Ballroom 2+3 Meeting Classroom 100 100 ## - Prospect Catherine Xu - -
苏州同元软控活动 SZ Tongyuan Software Group 8:30 12:30 TBA Meeting Classroom 100 100 ## - Prospect Catherine Xu - -
Event Start Date: 30/07/2026 (3 records)
中青�?-赛诺菲会�?CYTS--Sanofi 8:30 12:00 TBA Setup Existing Setup 10 10 10 - Prospect Cecily Hong - -
宁波银行 SZ Bank of Ningbo 8:30 17:30 Grand Ballroom Meeting Classroom 400 400 ## - Prospect Cecily Hong - -
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 31/07/2026 (3 records)
中青�?-赛诺菲会�?CYTS--Sanofi 8:30 22:00 TBA Meeting Existing Setup 300 270 ## - Prospect Cecily Hong - -
宁波银行 SZ Bank of Ningbo 8:30 17:30 Grand Ballroom Meeting Classroom 400 400 ## - Prospect Cecily Hong - -
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 01/08/2026 (5 records)
中信银行苏州分行会议 Citic Bank Meeting 6:00 18:00 Grand Ballroom 1 Meeting Fish Bone 90 90 90 - Prospect Luisa Liu Luisa Liu Luisa Liu
中信银行苏州分行会议 Citic Bank Meeting 12:00 18:00 VIP Room Room Hold Existing Setup 12 12 12 - Prospect Luisa Liu Luisa Liu Luisa Liu
中青�?-赛诺菲会�?CYTS--Sanofi 8:30 13:00 TBA Meeting Existing Setup 300 270 ## - Prospect Cecily Hong - -
宁波银行 SZ Bank of Ningbo 8:00 18:00 Grand Ballroom 2+3 Meeting Classroom 150 150 ## - Prospect Cecily Hong - -
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 02/08/2026 (1 record)
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 06/08/2026 (1 record)
赛默飞会�?CTS--Thermo Fisher 8:00 22:00 Grand Ballroom 1+2 Meeting Existing Setup 100 90 ## - Prospect Cecily Hong - -
Event Start Date: 07/08/2026 (3 records)
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
赛默飞会�?CTS--Thermo Fisher 8:00 18:00 Function Room 3+4 Meeting Existing Setup 50 50 50 - Prospect Cecily Hong - -
赛默飞会�?CTS--Thermo Fisher 8:00 18:00 Function Room 1 Meeting Existing Setup 50 50 50 - Prospect Cecily Hong - -
Event Start Date: 08/08/2026 (1 record)
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 09/08/2026 (1 record)
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 13/08/2026 (4 records)
广东大比特会�?Guangdong Dabit Meeting 6:00 18:00 Function Room 2+3+4 Meeting Classroom 60 60 60 - Definite Luisa Liu Luisa Liu Luisa Liu
广东大比特会�?Guangdong Dabit Meeting 0:00 22:00 Grand Ballroom Meeting Classroom 400 400 ## - Definite Luisa Liu Luisa Liu Luisa Liu
广东大比特会�?Guangdong Dabit Meeting 8:00 18:00 VIP Room Room Hold Existing Setup 12 12 12 - Definite Luisa Liu Luisa Liu Luisa Liu
广东大比特会�?Guangdong Dabit Meeting 6:00 18:00 Function Room 1 Meeting Classroom 60 60 60 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 21/08/2026 (1 record)
上海盛源--罗氏 shengyuan--Roche 1:00 22:00 Grand Ballroom Meeting Classroom 100 90 ## - Prospect Cecily Hong - -
Event Start Date: 22/08/2026 (3 records)
上海盛源--罗氏 shengyuan--Roche 8:00 18:00 Function Room 2+3+4 Meeting Classroom 50 40 50 - Prospect Cecily Hong - -
上海盛源--罗氏 shengyuan--Roche 8:00 22:00 Function Room 1 Meeting Classroom 50 40 50 - Prospect Cecily Hong - -
上海盛源--罗氏 shengyuan--Roche 8:00 18:00 Function Room 5+6 Meeting Theater 50 40 50 - Prospect Cecily Hong - -
Event Start Date: 28/08/2026 (1 record)
园区会员交流�?Nissho Club SIP party 12:00 21:00 Grand Ballroom 1+2 Dinner Buffet Round Tables of 10 140 120 ## - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 30/08/2026 (3 records)
谢东旭先生和胡迪小姐的婚�?有活动咨询宴会厅1请联系Elaine、婚宴可�?会增加桌数The Wedding of Mr. Xie and Ms. Hu 14:00 21:00 Rest Room/Bride Room Room Hold Existing Setup 8 6 8 - Definite Elaine He - -
谢东旭先生和胡迪小姐的婚�?有活动咨询宴会厅1请联系Elaine、婚宴可�?会增加桌数The Wedding of Mr. Xie and Ms. Hu 14:00 21:00 VIP Room Room Hold Existing Setup 15 12 15 - Definite Elaine He - -
谢东旭先生和胡迪小姐的婚�?有活动咨询宴会厅1请联系Elaine、婚宴可�?会增加桌数The Wedding of Mr. Xie and Ms. Hu 8:00 21:00 Grand Ballroom Wedding Dinner Round Tables of 10 200 200 ## - Definite Elaine He - -
Grand Totals (103 records)
Confidential Information - Do Not Distribute
Copyright (c) 2000-2026 salesforce.com, inc. All rights reserved.
"""

# Step 1: Parse
date_blocks = re.split(r'Event Start Date: ', RAW_TEXT)
event_blocks = []
for block in date_blocks:
    m = re.match(r'(\d{2}/\d{2}/\d{4}) \((\d+) records\)\n', block.strip())
    if m:
        day, month, year = m.group(1).split('/')
        iso_date = f"{year}-{month}-{day}"
        content = block[m.end():].strip()
        event_blocks.append((iso_date, int(m.group(2)), content))

print(f"Found {len(event_blocks)} date blocks")

# Parse events
all_events = []
rooms_pattern = r'(Grand Ballroom(?:\s+\d[\d\+]*)?|Function Room(?:\s+\d[\d\+\.,]*)?|Italian Restera(?:nt|urant)|Boardroom|VIP Room|Rest Room/Bride Room|Business Center|All Day Dining|OPEN|Bar Beer Society|BACIO|Function Room Foyer|Grand Ballroom Foyer|Coffee Break Area|TBA)'
owners_list = ["Elaine He", "Luisa Liu", "Lily Xie", "Nico Lin", "Cecily Hong", "Catherine Xu"]

for iso_date, count, content in event_blocks:
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line or line.startswith('Event Start Date:') or line.startswith('Grand Totals') or line.startswith('Confidential') or line.startswith('Copyright'):
            continue
        
        status = 'Definite'
        if 'Tentative' in line: status = 'Tentative'
        elif 'Prospect' in line: status = 'Prospect'
        
        time_match = re.findall(r'(\d{1,2}:\d{2})\s+(\d{1,2}:\d{2})', line)
        start_time = time_match[0][0] + ':00' if time_match else ''
        end_time = time_match[0][1] + ':00' if len(time_match) > 0 else ''
        
        room_match = re.search(rooms_pattern, line)
        room = room_match.group(0) if room_match else ''
        if 'All Day Dining' in line: room = 'All Day Dining OPEN'
        if 'Coffee Break' in line: room = line.split('Coffee Break')[0].strip()
        if 'Bar Beer' in line: room = 'Bar Beer Society'
        if 'Italian Restera' in line: room = 'Italian Restaurant BACIO'
        
        # Find the BEO number / Definite marker etc to split Chinese + English names
        beo_num = ''
        beo_match = re.search(r'(\d{4})[\s-]*(?:BEO|Definite)', line)
        if beo_match: beo_num = beo_match.group(1)
        
        # Try to extract Chinese name
        chn_name = ''
        eng_name = ''
        
        # Extract event name: look for Chinese chars before the time/room
        # Strategy: find the time pattern, then everything before the first time
        time_start_positions = [m.start() for m in re.finditer(r'\b\d{1,2}:\d{2}\b', line)]
        if time_start_positions:
            before_time = line[:time_start_positions[0]].strip()
            # Chinese chars before the time
            chn_chars = re.findall(r'[\u4e00-\u9fff《》—\-]+', before_time)
            chn_name = ' '.join(chn_chars) if chn_chars else ''
            # English after Chinese / before first time
            rest_before = before_time
            for c in chn_chars: rest_before = rest_before.replace(c, '').strip()
            eng_name = rest_before.strip()
        
        # Owner
        owner = ''
        for o in owners_list:
            if o in line: owner = o; break
        
        if chn_name or eng_name:
            all_events.append({
                'date': iso_date, 'chinese_name': chn_name, 'english_name': eng_name,
                'start': start_time, 'end': end_time,
                'room': room,
                'status': status, 'owner': owner, 'beo': beo_num
            })

print(f"Parsed {len(all_events)} events")

# Step 2: Import into FIN graph
shutil.copy(FIN_GRAPH, FIN_GRAPH.with_suffix('.pre_beo_20260621.json'))

with open(FIN_GRAPH, "r", encoding="utf-8") as f:
    fin = json.load(f)

def exists_in(entity_list, eid):
    return any(e.get('id') == eid for e in entity_list)

# Create report entity
REPORT_ID = "BEO_20260621"
if not exists_in(fin['entities'], REPORT_ID):
    fin['entities'].append({
        "id": REPORT_ID,
        "name": "BEO Daily Event 6.21-8.30",
        "type": "fin_report",
        "date": "2026-06-21",
        "properties": {
            "report_label": "BEO_SZVTV",
            "hotel": "Hilton Suzhou",
            "report_date": "2026-06-21",
            "filter_from": "2026-06-21",
            "filter_to": "2026-08-30",
            "total_events": len(all_events),
            "generated_by": "Elaine He",
            "source_file": "6.21-8.30Report.pdf",
            "imported_at": "2026-06-21"
        }
    })

# Link to FIN_YEAR_2026
FIN_YEAR = "FIN_YEAR_2026"
rel_key = f"REL_{REPORT_ID}_belongs_to_{FIN_YEAR}"
if not any(r.get('id') == rel_key for r in fin['relationships']):
    fin['relationships'].append({
        "source_id": REPORT_ID, "target_id": FIN_YEAR,
        "relation": "BELONGS_TO", "id": rel_key,
        "type": "BELONGS_TO", "source": REPORT_ID, "target": FIN_YEAR
    })

# Add events
new_count = 0
dup_count = 0

for e in all_events:
    safe_date = e['date'].replace('-', '')
    short_eng = (e['english_name'][:20] if e['english_name'] else e['chinese_name'][:10]).replace('/', '_').replace(' ', '_').replace('"', '').replace("'", '')
    short_eng = re.sub(r'[^a-zA-Z0-9_\u4e00-\u9fff]', '_', short_eng)
    event_id = f"BEO_{safe_date}_{short_eng}"
    
    if exists_in(fin['entities'], event_id):
        dup_count += 1
        continue
    
    fin['entities'].append({
        "id": event_id,
        "name": f"[BEO] {e['date']} {e['chinese_name']} {e['english_name'][:40]}",
        "type": "beo_event",
        "date": e['date'],
        "properties": {
            "date": e['date'], "event_date": e['date'],
            "chinese_name": e['chinese_name'], "english_name": e['english_name'],
            "start_time": e['start'], "end_time": e['end'],
            "room": e['room'],
            "status": e['status'], "owner": e['owner'], "beo_number": e['beo']
        }
    })
    new_count += 1
    
    event_rel = f"REL_{event_id}_belongs_to_{REPORT_ID}"
    if not any(r.get('id') == event_rel for r in fin['relationships']):
        fin['relationships'].append({
            "source_id": event_id, "target_id": REPORT_ID,
            "relation": "BELONGS_TO", "id": event_rel,
            "type": "BELONGS_TO", "source": event_id, "target": REPORT_ID
        })

# Update meta
fin['meta']['version'] = fin['meta'].get('version', '') + ' + BEO_6.21-8.30'
fin['meta']['updated'] = '2026-06-21 10:35'
fin['meta']['last_batch_import'] = 'BEO 6.21-8.30 Report'

with open(FIN_GRAPH, "w", encoding="utf-8") as f:
    json.dump(fin, f, ensure_ascii=False, indent=2)

event_by_status = {}
for e in all_events:
    s = e['status']
    event_by_status[s] = event_by_status.get(s, 0) + 1

print(f"\n�?Import complete!")
print(f"  New events added: {new_count}")
print(f"  Duplicates skipped: {dup_count}")
print(f"  Total FIN entities: {len(fin['entities'])}")
print(f"  Status breakdown: {event_by_status}")
print(f"  Date range: {event_blocks[0][0]} to {event_blocks[-1][0]}")
print(f"  Backup saved: fin_graph.pre_beo_20260621.json")
