"""Import BEO 6.6-7.30 Report into FIN graph"""
import json, re, shutil, sys
sys.stdout.reconfigure(encoding="utf-8")
from pathlib import Path
from collections import Counter

FIN_GRAPH = Path(r"C:\Users\Duke Wang\.openclaw\workspace\knowledge_center\fin_graph.json")

RAW_TEXT = """SZVTV Daily Event-BQ Generated By: Elaine He HM AP 1 06/06/2026 07:43 Sorted By: Booking Post As: Alternate Booking Post Booking Post As: Booking Post As: Start Time 24 End Time 24 Function Room Booking Event: Event Function Room Setup Expecte Guarantee Set BEO Event Booking Post As: Owner Booking Post As: Service Booking Post As: Catering
Event Start Date: 06/06/2026 (3 records)
华泰证券会议活动 Hua Tai Securities Co Ltd 13:30 18:00 Grand Ballroom 1 Meeting Classroom 110 100 ### Hua Tai Securities Co Ltd: 7700- Definite Elaine He Lily Xie Lily Xie
华泰证券会议活动 Hua Tai Securities Co Ltd 6:00 12:30 Grand Ballroom 1 Setup No Set Up Required 8 6 8 Hua Tai Securities Co Ltd: 7700- Definite Elaine He Lily Xie Lily Xie
金山办公 ——6 月教育业务专题会 Kingsoft Office Meeting 8:00 18:00 Function Room 3+4 Meeting Fish Bone 50 45 50 Kingsoft Office: 7698-BEO Definite Cecily Hong - Lily Xie
金山办公 ——6 月教育业务专题会 Kingsoft Office Meeting 8:00 18:00 Function Room 3+4 Meeting Fish Bone 50 45 50 Kingsoft Office: 7699-BEO Definite Cecily Hong - Lily Xie
HR 内部使用 -TWAM 员工活动 Block of HR 10:00 16:30 Function Room 1 Activities/Recreation Special Setup 30 30 30 - Prospect Nico Lin - -
Event Start Date: 07/06/2026 (1 record)
《建筑结构》杂志社会议 Architectural Structure Magazine Meeting 17:00 21:00 Function Room 1 Dinner Round Tables of 10 40 40 40 - Definite Cecily Hong - Lily Xie
《建筑结构》杂志社会议 Architectural Structure Magazine Meeting 8:00 18:00 Grand Ballroom Meeting Classroom 200 180 ### - Definite Cecily Hong - Lily Xie
《建筑结构》杂志社会议 Architectural Structure Magazine Meeting 12:00 13:30 All Day Dining OPEN Lunch Buffet Existing Setup 50 50 50 - Definite Cecily Hong - Lily Xie
《建筑结构》杂志社会议 Architectural Structure Magazine Meeting 8:00 18:00 VIP Room Reception Existing Setup 10 10 10 - Definite Cecily Hong - Lily Xie
《建筑结构》杂志社会议 Architectural Structure Magazine Meeting 11:00 14:00 Function Room 6 Lunch Round Tables of 10 20 20 20 - Definite Cecily Hong - Lily Xie
上海乾飞研讨会 Shanghai Qianfei Meeting 8:00 17:00 Function Room 2+3+4 Meeting Classroom 70 70 70 - Definite Lily Xie - Catherine Xu
亚太传媒 - 涉外法治会议 GRCD meeting 13:30 17:30 Function Room 1 Meeting Classroom 70 70 70 - Definite Nico Lin - -
亚太传媒 - 涉外法治会议 GRCD meeting 15:00 15:30 Function Room Foyer Break PM Coffee Station 50 50 50 - Definite Nico Lin - -
Event Start Date: 10/06/2026 (1 record)
王浩先生和史雪晨小姐的婚宴 The Wedding of Mr. Wang and Ms. Shi 8:00 21:00 Grand Ballroom 1 Wedding Dinner Round Tables of 10 60 60 60 - Definite Elaine He - -
王浩先生和史雪晨小姐的婚宴 The Wedding of Mr. Wang and Ms. Shi 12:00 21:00 VIP Room Room Hold Existing Setup 8 6 8 - Definite Elaine He - -
Event Start Date: 11/06/2026 (1 record)
诺和诺德会议 Novo Nordisk meeting 18:00 18:30 Function Room 6 Boxed Dinner Round Tables of 10 10 10 10 - Definite Nico Lin - -
Event Start Date: 12/06/2026 (7 records)
默沙东会议 MSD meeting 8:30 12:30 Function Room 3+4 Meeting - 60 60 60 - Tentative Nico Lin - -
张先生家婚礼答谢晚宴 The Dinner of Mr.Zhang 13:00 21:00 Function Room 2+3+4 Wedding Dinner Round Tables of 10 80 70 80 - Definite Lily Xie - -
浙江光大国际旅行社 ZJ Guangda Tour Group 8:30 17:30 Function Room 6 Meeting Classroom 20 20 20 - Tentative Catherine Xu - -
诺和诺德会议 Novo Nordisk meeting 8:00 12:30 Grand Ballroom 1 Meeting Classroom 60 60 60 - Definite Nico Lin - -
诺和诺德会议 Novo Nordisk meeting 10:00 10:30 Grand Ballroom Foyer Break AM Coffee Station 40 40 40 - Definite Nico Lin - -
Event Start Date: 13/06/2026 (4 records)
鲍承祖先生和姜文静小姐的婚宴 宴会厅 1 报价之前问下园园； The Wedding of Mr. Bao and Ms. Jiang 7:00 14:00 Grand Ballroom 2+3 Lunch Buffet Special Setup Instructions 180 180 ### - Definite Elaine He - -
鲍承祖先生和姜文静小姐的婚宴 宴会厅 1 报价之前问下园园； The Wedding of Mr. Bao and Ms. Jiang 10:00 14:00 VIP Room Room Hold Existing Setup 14 12 14 - Definite Elaine He - -
Event Start Date: 14/06/2026 (6 records)
三人行 - 中国移动会议 Three's Company Media Meeting 7:00 18:00 Grand Ballroom Meeting Classroom 150 150 ### - Prospect Luisa Liu Luisa Liu Luisa Liu
天泰焊材管理层会议 Tientai Management Meeting 10:00 10:30 Function Room Foyer Break AM Coffee Station 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
天泰焊材管理层会议 Tientai Management Meeting 8:00 18:00 Function Room 2+3+4 Meeting U Shape 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
天泰焊材管理层会议 Tientai Management Meeting 15:00 15:30 Function Room Foyer Break PM Coffee Station 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
天泰焊材管理层会议 Tientai Management Meeting 18:00 20:30 Function Room 1 Dinner Round Tables of 10 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 16/06/2026 (1 record)
于主任家的宝宝宴 The Birthday Lunch of Ms. Yu 8:00 14:00 Function Room 3+4 Lunch Round Tables of 10 40 40 40 - Prospect Elaine He - -
Event Start Date: 17/06/2026 (4 records)
杜老师孙儿周岁午宴 Mrs.Du's grandson ceromony lunch 11:30 14:30 Function Room 3+4 Lunch Round Tables of 10 30 30 30 - Definite Luisa Liu Luisa Liu Luisa Liu
杜老师孙儿周岁午宴 Mrs.Du's grandson ceromony lunch 7:00 11:00 Function Room 3+4 Setup Round Tables of 10 2 2 2 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 18/06/2026 (4 records)
东方财富活动 Oriental Wealth Securities Group 9:00 18:00 Grand Ballroom 2+3 Meeting Classroom 200 200 ### - Prospect Catherine Xu - -
Event Start Date: 19/07/2026 (3 records)
西门子会议 Simens Suzhou Branch Meeting 12:00 17:00 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Lily Xie - -
西门子会议 Simens Suzhou Branch Meeting 18:00 21:00 Function Room 1 Dinner Round Tables of 10 50 50 50 - Prospect Lily Xie - -
Event Start Date: 20/06/2026 (1 record)
江苏省招标中心会议 Jiangsu Bidding Center Meeting 8:00 18:00 Function Room 3+4 Meeting Hollow Square 40 40 40 - Tentative Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 21/06/2026 (2 records)
苏州联政智能会议 SZ lianzheng zhineng meeting 9:00 18:00 Grand Ballroom 1 Meeting Classroom 100 100 ### - Prospect Lily Xie - -
广州康普基金会 -MSD 活动 Guangzhou Pukang Meeting 12:00 17:00 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Lily Xie - -
数智医学研究中心会议 Digital Intelligence Medical Research Center 8:00 18:00 Grand Ballroom 2+3 Meeting Existing Setup 80 70 80 - Prospect Cecily Hong - -
Event Start Date: 24/06/2026 (1 record)
朴女士家的宝宝宴 The lunch of Ms. piao 11:00 14:00 Grand Ballroom 1 Lunch Round Tables of 10 80 80 80 - Definite Nico Lin - -
朴女士家的宝宝宴 The lunch of Ms. piao 12:00 14:00 VIP Room Room Hold Existing Setup 5 5 5 - Definite Nico Lin - -
朴女士家的宝宝宴 The lunch of Ms. piao 8:00 11:00 Grand Ballroom 1 Setup Existing Setup 5 5 5 - Definite Nico Lin - -
Event Start Date: 25/06/2026 (2 records)
上海歆思 -MSD SHA Xinsi-MSD Group 8:30 17:30 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Catherine Xu - -
Event Start Date: 26/06/2026 (2 records)
研华科技活动 Beijing Advantech Xingye Electronic Technology 10:00 18:00 VIP Room Meeting Existing Setup 8 6 8 - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 7:00 18:00 Grand Ballroom Meeting Classroom 500 500 ### - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 10:00 18:00 Business Center Meeting Room Hold Existing Setup 8 6 8 - Definite Elaine He - -
上海赛福化工会议 Shanghai Sai Fu meeting 8:30 17:30 Function Room 1 Meeting Classroom 50 50 50 - Prospect Nico Lin - Elaine He
研华科技活动 Beijing Advantech Xingye Electronic Technology 13:30 18:00 Function Room 4 Meeting Classroom 30 20 30 - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 12:00 13:00 Bar Beer Society Lunch Buffet Existing Setup 100 100 ### - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 12:00 13:00 Italian Resterant BACIO Lunch Buffet Existing Setup 80 80 80 - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 12:00 13:00 All Day Dining OPEN Lunch Buffet Existing Setup 150 150 ### - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 8:30 18:00 Grand Ballroom Foyer Break Coffee Station 200 200 ### - Definite Elaine He - -
研华科技活动 Beijing Advantech Xingye Electronic Technology 15:00 15:30 Grand Ballroom Foyer Break PM Coffee Station 250 250 ### - Definite Elaine He - -
Event Start Date: 27/06/2026 (5 records)
中科看点活动 Zhongke Kandian Meeting 12:00 17:30 Grand Ballroom 3 Meeting Classroom 105 105 ### - Prospect Nico Lin - -
中科看点活动 Zhongke Kandian Meeting 11:00 17:30 Rest Room/Bride Room Setup Existing Setup 10 10 10 - Prospect Nico Lin - -
Event Start Date: 28/06/2026 (1 record)
罗氏会议 Roche meeting 8:30 18:00 Function Room 6 Meeting Classroom 40 40 40 - Prospect Cecily Hong - Nico Lin
罗氏会议 Roche meeting 8:30 18:00 Boardroom Meeting Existing Setup 40 40 40 - Prospect Cecily Hong - Nico Lin
苏州音为梦组织钢琴比赛 Suzhou Yinfeng Dream Art Piano competition 7:00 17:30 Function Room 1 Meeting Theater 80 80 80 - Prospect Nico Lin - -
苏州音为梦组织钢琴比赛 Suzhou Yinfeng Dream Art Piano competition 18:00 21:00 Function Room 2 Dinner Round Tables of 10 20 20 20 - Prospect Nico Lin - -
Event Start Date: 01/07/2026 (3 records)
西门子机床客户日 Siemens Meeting 5:00 23:00 Grand Ballroom Setup Existing Setup 10 10 10 - Prospect Cecily Hong - -
新东方教育展 - Suzhou New Oriental School Meeting 9:00 18:00 Grand Ballroom Meeting Classroom 300 300 ### - Prospect Lily Xie - -
西门子机床客户日 Siemens Meeting 8:00 22:00 TBA Meeting Classroom 600 550 ### - Prospect Cecily Hong - -
Event Start Date: 02/07/2026 (7 records)
华星光电杨先生同学会晚宴 Star Optoelectronic Dinner 16:15 21:00 Function Room 2+3+4 Dinner Round Tables of 10 80 70 80 - Prospect Lily Xie - -
西门子机床客户日 Siemens Meeting 8:00 22:00 Grand Ballroom Meeting - 200 180 ### - Prospect Cecily Hong - -
上海维度 --IT SHA WeiDu--IT 8:00 22:00 Grand Ballroom 2+3 Meeting Existing Setup 250 230 ### - Prospect Cecily Hong - -
Event Start Date: 03/07/2026 (2 records)
陈先生家升学宴 Thanks Dinner of Mr.Chen 15:00 21:00 Grand Ballroom 1 Dinner Round Tables of 10 70 70 70 - Prospect Luisa Liu Luisa Liu Luisa Liu
陈先生家升学宴 Thanks Dinner of Mr.Chen 13:00 21:00 VIP Room Room Hold Existing Setup 20 20 20 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 04/07/2026 (2 records)
上海维度 --IT SHA WeiDu--IT 8:00 18:00 Grand Ballroom Meeting Existing Setup 250 230 ### - Prospect Cecily Hong - -
Event Start Date: 05/07/2026 (2 records)
诺和诺德会议 Novo Nordisk Meeting 8:00 22:00 Grand Ballroom Meeting Classroom 300 270 ### - Prospect Cecily Hong - -
诺和诺德会议 Novo Nordisk Meeting 8:00 18:00 Function Room 5+6 Meeting Fish Bone 40 35 40 - Prospect Cecily Hong - -
诺和诺德会议 Novo Nordisk Meeting 8:00 18:00 Function Room 1 Meeting Fish Bone 40 35 40 - Prospect Cecily Hong - -
诺和诺德会议 Novo Nordisk Meeting 8:00 18:00 Function Room 2+3+4 Meeting Fish Bone 40 35 40 - Prospect Cecily Hong - -
Event Start Date: 09/07/2026 (1 record)
赛默飞会议 Thermo Fisher Meeting 7:00 18:00 Function Room 2+3+4 Meeting Classroom 63 63 63 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 10/07/2026 (2 records)
李先生订婚午宴 Mr.Li's Engagement Lunch 7:00 15:00 Grand Ballroom 1 Lunch Round Tables of 10 100 90 ### - Definite Luisa Liu Nico Lin Nico Lin
Event Start Date: 11/07/2026 (2 records)
渣打银行会议 Standard Chartered Bank Meeting 7:00 17:00 Grand Ballroom 3 Meeting Classroom 72 63 63 - Definite Luisa Liu Luisa Liu Luisa Liu
渣打银行会议 Standard Chartered Bank Meeting 15:00 15:30 Grand Ballroom Foyer Break PM Coffee Station 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
渣打银行会议 Standard Chartered Bank Meeting 7:00 11:00 Grand Ballroom 3 Setup Classroom 2 2 2 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 12/07/2026 (3 records)
沈书记家的宝宝宴 The Baby Lunch of Mr. Shen 8:00 14:00 Grand Ballroom 1+2 Lunch Round Tables of 10 180 180 ### - Definite Elaine He - -
沈书记家的宝宝宴 The Baby Lunch of Mr. Shen 8:00 14:00 VIP Room Room Hold Existing Setup 15 12 15 - Definite Elaine He - -
沈书记家的宝宝宴 The Baby Lunch of Mr. Shen 8:00 14:00 Rest Room/Bride Room Room Hold No Set Up Required 8 6 8 - Definite Elaine He - -
Event Start Date: 13/07/2026 (1 record)
中科看点活动 Zhongke Kandian Meeting 12:00 17:30 Grand Ballroom 3 Meeting Classroom 105 105 ### - Prospect Nico Lin - -
中科看点活动 Zhongke Kandian Meeting 11:00 17:30 Rest Room/Bride Room Setup Existing Setup 10 10 10 - Prospect Nico Lin - -
Event Start Date: 14/07/2026 (1 record)
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
苏州云慧家庭咨询 Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
"""

# Step 1: Parse
date_blocks = re.split(r'Event Start Date: ', RAW_TEXT)
event_blocks = []
for block in date_blocks:
    m = re.match(r'(\d{2}/\d{2}/\d{4}) \((\d+) records\)\n', block.strip())
    if m:
        day, month, year = m.group(1).split('/')
        iso_date = f"{year}-{month}-{day}"
        content = block[m.end():].strip()
        event_blocks.append((iso_date, int(m.group(2)), content))

print(f"Found {len(event_blocks)} date blocks")

# Parse events
all_events = []
rooms_pattern = r'(Grand Ballroom(?:\s+\d[\d\+]*)?|Function Room(?:\s+\d[\d\+\.,]*)?|Italian Restera(?:nt|urant)|Boardroom|VIP Room|Rest Room/Bride Room|Business Center|All Day Dining|OPEN|Bar Beer Society|BACIO|Function Room Foyer|Grand Ballroom Foyer|TBA)'
setup_patterns = r'(Lunch Buffet|Wedding Dinner|Meeting|Lunch|Dinner|Dinner Round Tables|Setup|Break|Room Hold|Boxed Dinner|Coffee Station|Activities/Recreation|Special Setup|Reception)'
owners_list = ["Elaine He", "Luisa Liu", "Lily Xie", "Nico Lin", "Cecily Hong", "Catherine Xu"]
event_name_pattern = r'(The (Wedding|Lunch|Dinner|Thanks|Birthday|Baby|dinner|Dinner|Lunch)\s+of\s+[\w\s.]+|Meeting|[\w\s]+Meeting|[\w\s]+Group)'

for iso_date, count, content in event_blocks:
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line or line.startswith('Event Start Date:') or line.startswith('Grand Totals'):
            continue
        
        status = 'Definite'
        if 'Tentative' in line: status = 'Tentative'
        elif 'Prospect' in line: status = 'Prospect'
        
        time_match = re.findall(r'(\d{1,2}:\d{2})\s+(\d{1,2}:\d{2})', line)
        start_time = time_match[0][0] + ':00' if time_match else ''
        end_time = time_match[0][1] + ':00' if len(time_match) > 0 else ''
        
        room_match = re.search(rooms_pattern, line)
        setup_match = re.search(setup_patterns, line)
        
        eng_match = re.search(event_name_pattern, line)
        eng_name = eng_match.group(0) if eng_match else ''
        
        # Chinese name
        chn_name = ''
        if eng_match:
            idx = line.find(eng_match.group(0))
            if idx > 0:
                potential_chn = line[:idx].strip()
                chn_chars = re.findall(r'[\u4e00-\u9fff《》—\-]+', potential_chn)
                chn_name = ' '.join(chn_chars) if chn_chars else ''
        
        # BEO number
        beo_num = ''
        beo_num_match = re.search(r'(\d{4})[-\s]*(?:BEO|Definite)', line)
        if beo_num_match: beo_num = beo_num_match.group(1)
        
        # Owner
        owner = ''
        for o in owners_list:
            if o in line: owner = o; break
        
        if chn_name or eng_name:
            all_events.append({
                'date': iso_date, 'chinese_name': chn_name, 'english_name': eng_name,
                'start': start_time, 'end': end_time,
                'room': room_match.group(0) if room_match else '',
                'setup': setup_match.group(0) if setup_match else '',
                'status': status, 'owner': owner, 'beo': beo_num
            })

print(f"Parsed {len(all_events)} events")

# Step 2: Import into FIN graph
shutil.copy(FIN_GRAPH, FIN_GRAPH.with_suffix('.pre_beo_20260606.json'))

with open(FIN_GRAPH, "r", encoding="utf-8") as f:
    fin = json.load(f)

def exists_in(entity_list, eid):
    return any(e.get('id') == eid for e in entity_list)

# Create report entity
REPORT_ID = "BEO_20260606"
if not exists_in(fin['entities'], REPORT_ID):
    fin['entities'].append({
        "id": REPORT_ID,
        "name": "BEO Daily Event 6.6-7.30",
        "type": "fin_report",
        "date": "2026-06-06",
        "properties": {
            "report_label": "BEO_SZVTV",
            "hotel": "Hilton Suzhou",
            "report_date": "2026-06-06",
            "filter_from": "2026-06-06",
            "filter_to": "2026-07-30",
            "total_events": len(all_events),
            "generated_by": "Elaine He",
            "source_file": "6.6-7.30Report.pdf",
            "imported_at": "2026-06-06"
        }
    })

# Link to FIN_YEAR_2026
FIN_YEAR = "FIN_YEAR_2026"
rel_key = f"REL_{REPORT_ID}_belongs_to_{FIN_YEAR}"
if not any(r.get('id') == rel_key for r in fin['relationships']):
    fin['relationships'].append({
        "source_id": REPORT_ID, "target_id": FIN_YEAR,
        "relation": "BELONGS_TO", "id": rel_key,
        "type": "BELONGS_TO", "source": REPORT_ID, "target": FIN_YEAR
    })

# Add events
event_count_by_status = Counter(e['status'] for e in all_events)
new_count = 0

for e in all_events:
    safe_date = e['date'].replace('-', '')
    short_name = (e['english_name'][:20] if e['english_name'] else e['chinese_name'][:10]).replace('/', '_').replace(' ', '_')
    event_id = f"BEO_{safe_date}_{short_name}"
    
    if exists_in(fin['entities'], event_id):
        continue
    
    fin['entities'].append({
        "id": event_id,
        "name": f"[BEO] {e['date']} {e['chinese_name']} {e['english_name'][:40]}",
        "type": "beo_event",
        "date": e['date'],
        "properties": {
            "date": e['date'], "event_date": e['date'],
            "chinese_name": e['chinese_name'], "english_name": e['english_name'],
            "start_time": e['start'], "end_time": e['end'],
            "room": e['room'], "setup": e['setup'],
            "status": e['status'], "owner": e['owner'], "beo_number": e['beo']
        }
    })
    new_count += 1
    
    event_rel = f"REL_{event_id}_belongs_to_{REPORT_ID}"
    if not any(r.get('id') == event_rel for r in fin['relationships']):
        fin['relationships'].append({
            "source_id": event_id, "target_id": REPORT_ID,
            "relation": "BELONGS_TO", "id": event_rel,
            "type": "BELONGS_TO", "source": event_id, "target": REPORT_ID
        })

# Update meta
fin['meta']['version'] = fin['meta'].get('version', '') + ' + BEO_6.6-7.30'
fin['meta']['updated'] = '2026-06-06 09:15'
fin['meta']['last_batch_import'] = 'BEO 6.6-7.30 Report'

with open(FIN_GRAPH, "w", encoding="utf-8") as f:
    json.dump(fin, f, ensure_ascii=False, indent=2)

print(f"\n✅ Import complete!")
print(f"  New events added: {new_count}")
print(f"  Total FIN entities: {len(fin['entities'])}")
print(f"  Status breakdown: {dict(event_count_by_status)}")
print(f"  Date range: {event_blocks[0][0]} to {event_blocks[-1][0]}")
print(f"  Backup saved: fin_graph.pre_beo_20260606.json")
