"""Import BEO 6.6-7.30 Report into FIN graph"""
import json, re, shutil, sys
sys.stdout.reconfigure(encoding="utf-8")
from pathlib import Path
from collections import Counter

FIN_GRAPH = Path(r"C:\Users\Y\.openclaw\workspace\knowledge_center\fin_graph.json")

RAW_TEXT = """SZVTV Daily Event-BQ Generated By: Elaine He HM AP 1 06/06/2026 07:43 Sorted By: Booking Post As: Alternate Booking Post Booking Post As: Booking Post As: Start Time 24 End Time 24 Function Room Booking Event: Event Function Room Setup Expecte Guarantee Set BEO Event Booking Post As: Owner Booking Post As: Service Booking Post As: Catering
Event Start Date: 06/06/2026 (3 records)
åŽæ³°è¯åˆ¸ä¼šè®®æ´»åŠ¨ Hua Tai Securities Co Ltd 13:30 18:00 Grand Ballroom 1 Meeting Classroom 110 100 ### Hua Tai Securities Co Ltd: 7700- Definite Elaine He Lily Xie Lily Xie
åŽæ³°è¯åˆ¸ä¼šè®®æ´»åŠ¨ Hua Tai Securities Co Ltd 6:00 12:30 Grand Ballroom 1 Setup No Set Up Required 8 6 8 Hua Tai Securities Co Ltd: 7700- Definite Elaine He Lily Xie Lily Xie
é‡‘å±±åŠžå…¬ â€”â€? æœˆæ•™è‚²ä¸šåŠ¡ä¸“é¢˜ä¼š Kingsoft Office Meeting 8:00 18:00 Function Room 3+4 Meeting Fish Bone 50 45 50 Kingsoft Office: 7698-BEO Definite Cecily Hong - Lily Xie
é‡‘å±±åŠžå…¬ â€”â€? æœˆæ•™è‚²ä¸šåŠ¡ä¸“é¢˜ä¼š Kingsoft Office Meeting 8:00 18:00 Function Room 3+4 Meeting Fish Bone 50 45 50 Kingsoft Office: 7699-BEO Definite Cecily Hong - Lily Xie
HR å†…éƒ¨ä½¿ç”¨ -TWAM å‘˜å·¥æ´»åŠ¨ Block of HR 10:00 16:30 Function Room 1 Activities/Recreation Special Setup 30 30 30 - Prospect Nico Lin - -
Event Start Date: 07/06/2026 (1 record)
ã€Šå»ºç­‘ç»“æž„ã€‹æ‚å¿—ç¤¾ä¼šè®® Architectural Structure Magazine Meeting 17:00 21:00 Function Room 1 Dinner Round Tables of 10 40 40 40 - Definite Cecily Hong - Lily Xie
ã€Šå»ºç­‘ç»“æž„ã€‹æ‚å¿—ç¤¾ä¼šè®® Architectural Structure Magazine Meeting 8:00 18:00 Grand Ballroom Meeting Classroom 200 180 ### - Definite Cecily Hong - Lily Xie
ã€Šå»ºç­‘ç»“æž„ã€‹æ‚å¿—ç¤¾ä¼šè®® Architectural Structure Magazine Meeting 12:00 13:30 All Day Dining OPEN Lunch Buffet Existing Setup 50 50 50 - Definite Cecily Hong - Lily Xie
ã€Šå»ºç­‘ç»“æž„ã€‹æ‚å¿—ç¤¾ä¼šè®® Architectural Structure Magazine Meeting 8:00 18:00 VIP Room Reception Existing Setup 10 10 10 - Definite Cecily Hong - Lily Xie
ã€Šå»ºç­‘ç»“æž„ã€‹æ‚å¿—ç¤¾ä¼šè®® Architectural Structure Magazine Meeting 11:00 14:00 Function Room 6 Lunch Round Tables of 10 20 20 20 - Definite Cecily Hong - Lily Xie
ä¸Šæµ·ä¹¾é£žç ”è®¨ä¼?Shanghai Qianfei Meeting 8:00 17:00 Function Room 2+3+4 Meeting Classroom 70 70 70 - Definite Lily Xie - Catherine Xu
äºšå¤ªä¼ åª’ - æ¶‰å¤–æ³•æ²»ä¼šè®® GRCD meeting 13:30 17:30 Function Room 1 Meeting Classroom 70 70 70 - Definite Nico Lin - -
äºšå¤ªä¼ åª’ - æ¶‰å¤–æ³•æ²»ä¼šè®® GRCD meeting 15:00 15:30 Function Room Foyer Break PM Coffee Station 50 50 50 - Definite Nico Lin - -
Event Start Date: 10/06/2026 (1 record)
çŽ‹æµ©å…ˆç”Ÿå’Œå²é›ªæ™¨å°å§çš„å©šå®?The Wedding of Mr. Wang and Ms. Shi 8:00 21:00 Grand Ballroom 1 Wedding Dinner Round Tables of 10 60 60 60 - Definite Elaine He - -
çŽ‹æµ©å…ˆç”Ÿå’Œå²é›ªæ™¨å°å§çš„å©šå®?The Wedding of Mr. Wang and Ms. Shi 12:00 21:00 VIP Room Room Hold Existing Setup 8 6 8 - Definite Elaine He - -
Event Start Date: 11/06/2026 (1 record)
è¯ºå’Œè¯ºå¾·ä¼šè®® Novo Nordisk meeting 18:00 18:30 Function Room 6 Boxed Dinner Round Tables of 10 10 10 10 - Definite Nico Lin - -
Event Start Date: 12/06/2026 (7 records)
é»˜æ²™ä¸œä¼šè®?MSD meeting 8:30 12:30 Function Room 3+4 Meeting - 60 60 60 - Tentative Nico Lin - -
å¼ å…ˆç”Ÿå®¶å©šç¤¼ç­”è°¢æ™šå®´ The Dinner of Mr.Zhang 13:00 21:00 Function Room 2+3+4 Wedding Dinner Round Tables of 10 80 70 80 - Definite Lily Xie - -
æµ™æ±Ÿå…‰å¤§å›½é™…æ—…è¡Œç¤?ZJ Guangda Tour Group 8:30 17:30 Function Room 6 Meeting Classroom 20 20 20 - Tentative Catherine Xu - -
è¯ºå’Œè¯ºå¾·ä¼šè®® Novo Nordisk meeting 8:00 12:30 Grand Ballroom 1 Meeting Classroom 60 60 60 - Definite Nico Lin - -
è¯ºå’Œè¯ºå¾·ä¼šè®® Novo Nordisk meeting 10:00 10:30 Grand Ballroom Foyer Break AM Coffee Station 40 40 40 - Definite Nico Lin - -
Event Start Date: 13/06/2026 (4 records)
é²æ‰¿ç¥–å…ˆç”Ÿå’Œå§œæ–‡é™å°å§çš„å©šå®´ å®´ä¼šåŽ?1 æŠ¥ä»·ä¹‹å‰é—®ä¸‹å›­å›­ï¼?The Wedding of Mr. Bao and Ms. Jiang 7:00 14:00 Grand Ballroom 2+3 Lunch Buffet Special Setup Instructions 180 180 ### - Definite Elaine He - -
é²æ‰¿ç¥–å…ˆç”Ÿå’Œå§œæ–‡é™å°å§çš„å©šå®´ å®´ä¼šåŽ?1 æŠ¥ä»·ä¹‹å‰é—®ä¸‹å›­å›­ï¼?The Wedding of Mr. Bao and Ms. Jiang 10:00 14:00 VIP Room Room Hold Existing Setup 14 12 14 - Definite Elaine He - -
Event Start Date: 14/06/2026 (6 records)
ä¸‰äººè¡?- ä¸­å›½ç§»åŠ¨ä¼šè®® Three's Company Media Meeting 7:00 18:00 Grand Ballroom Meeting Classroom 150 150 ### - Prospect Luisa Liu Luisa Liu Luisa Liu
å¤©æ³°ç„Šæç®¡ç†å±‚ä¼šè®?Tientai Management Meeting 10:00 10:30 Function Room Foyer Break AM Coffee Station 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
å¤©æ³°ç„Šæç®¡ç†å±‚ä¼šè®?Tientai Management Meeting 8:00 18:00 Function Room 2+3+4 Meeting U Shape 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
å¤©æ³°ç„Šæç®¡ç†å±‚ä¼šè®?Tientai Management Meeting 15:00 15:30 Function Room Foyer Break PM Coffee Station 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
å¤©æ³°ç„Šæç®¡ç†å±‚ä¼šè®?Tientai Management Meeting 18:00 20:30 Function Room 1 Dinner Round Tables of 10 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 16/06/2026 (1 record)
äºŽä¸»ä»»å®¶çš„å®å®å®´ The Birthday Lunch of Ms. Yu 8:00 14:00 Function Room 3+4 Lunch Round Tables of 10 40 40 40 - Prospect Elaine He - -
Event Start Date: 17/06/2026 (4 records)
æœè€å¸ˆå­™å„¿å‘¨å²åˆå®´ Mrs.Du's grandson ceromony lunch 11:30 14:30 Function Room 3+4 Lunch Round Tables of 10 30 30 30 - Definite Luisa Liu Luisa Liu Luisa Liu
æœè€å¸ˆå­™å„¿å‘¨å²åˆå®´ Mrs.Du's grandson ceromony lunch 7:00 11:00 Function Room 3+4 Setup Round Tables of 10 2 2 2 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 18/06/2026 (4 records)
ä¸œæ–¹è´¢å¯Œæ´»åŠ¨ Oriental Wealth Securities Group 9:00 18:00 Grand Ballroom 2+3 Meeting Classroom 200 200 ### - Prospect Catherine Xu - -
Event Start Date: 19/07/2026 (3 records)
è¥¿é—¨å­ä¼šè®?Simens Suzhou Branch Meeting 12:00 17:00 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Lily Xie - -
è¥¿é—¨å­ä¼šè®?Simens Suzhou Branch Meeting 18:00 21:00 Function Room 1 Dinner Round Tables of 10 50 50 50 - Prospect Lily Xie - -
Event Start Date: 20/06/2026 (1 record)
æ±Ÿè‹çœæ‹›æ ‡ä¸­å¿ƒä¼šè®?Jiangsu Bidding Center Meeting 8:00 18:00 Function Room 3+4 Meeting Hollow Square 40 40 40 - Tentative Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 21/06/2026 (2 records)
è‹å·žè”æ”¿æ™ºèƒ½ä¼šè®® SZ lianzheng zhineng meeting 9:00 18:00 Grand Ballroom 1 Meeting Classroom 100 100 ### - Prospect Lily Xie - -
å¹¿å·žåº·æ™®åŸºé‡‘ä¼?-MSD æ´»åŠ¨ Guangzhou Pukang Meeting 12:00 17:00 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Lily Xie - -
æ•°æ™ºåŒ»å­¦ç ”ç©¶ä¸­å¿ƒä¼šè®® Digital Intelligence Medical Research Center 8:00 18:00 Grand Ballroom 2+3 Meeting Existing Setup 80 70 80 - Prospect Cecily Hong - -
Event Start Date: 24/06/2026 (1 record)
æœ´å¥³å£«å®¶çš„å®å®å®´ The lunch of Ms. piao 11:00 14:00 Grand Ballroom 1 Lunch Round Tables of 10 80 80 80 - Definite Nico Lin - -
æœ´å¥³å£«å®¶çš„å®å®å®´ The lunch of Ms. piao 12:00 14:00 VIP Room Room Hold Existing Setup 5 5 5 - Definite Nico Lin - -
æœ´å¥³å£«å®¶çš„å®å®å®´ The lunch of Ms. piao 8:00 11:00 Grand Ballroom 1 Setup Existing Setup 5 5 5 - Definite Nico Lin - -
Event Start Date: 25/06/2026 (2 records)
ä¸Šæµ·æ­†æ€?-MSD SHA Xinsi-MSD Group 8:30 17:30 Function Room 3+4 Meeting Classroom 60 60 60 - Prospect Catherine Xu - -
Event Start Date: 26/06/2026 (2 records)
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 10:00 18:00 VIP Room Meeting Existing Setup 8 6 8 - Definite Elaine He - -
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 7:00 18:00 Grand Ballroom Meeting Classroom 500 500 ### - Definite Elaine He - -
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 10:00 18:00 Business Center Meeting Room Hold Existing Setup 8 6 8 - Definite Elaine He - -
ä¸Šæµ·èµ›ç¦åŒ–å·¥ä¼šè®® Shanghai Sai Fu meeting 8:30 17:30 Function Room 1 Meeting Classroom 50 50 50 - Prospect Nico Lin - Elaine He
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 13:30 18:00 Function Room 4 Meeting Classroom 30 20 30 - Definite Elaine He - -
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 12:00 13:00 Bar Beer Society Lunch Buffet Existing Setup 100 100 ### - Definite Elaine He - -
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 12:00 13:00 Italian Resterant BACIO Lunch Buffet Existing Setup 80 80 80 - Definite Elaine He - -
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 12:00 13:00 All Day Dining OPEN Lunch Buffet Existing Setup 150 150 ### - Definite Elaine He - -
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 8:30 18:00 Grand Ballroom Foyer Break Coffee Station 200 200 ### - Definite Elaine He - -
ç ”åŽç§‘æŠ€æ´»åŠ¨ Beijing Advantech Xingye Electronic Technology 15:00 15:30 Grand Ballroom Foyer Break PM Coffee Station 250 250 ### - Definite Elaine He - -
Event Start Date: 27/06/2026 (5 records)
ä¸­ç§‘çœ‹ç‚¹æ´»åŠ¨ Zhongke Kandian Meeting 12:00 17:30 Grand Ballroom 3 Meeting Classroom 105 105 ### - Prospect Nico Lin - -
ä¸­ç§‘çœ‹ç‚¹æ´»åŠ¨ Zhongke Kandian Meeting 11:00 17:30 Rest Room/Bride Room Setup Existing Setup 10 10 10 - Prospect Nico Lin - -
Event Start Date: 28/06/2026 (1 record)
ç½—æ°ä¼šè®® Roche meeting 8:30 18:00 Function Room 6 Meeting Classroom 40 40 40 - Prospect Cecily Hong - Nico Lin
ç½—æ°ä¼šè®® Roche meeting 8:30 18:00 Boardroom Meeting Existing Setup 40 40 40 - Prospect Cecily Hong - Nico Lin
è‹å·žéŸ³ä¸ºæ¢¦ç»„ç»‡é’¢ç´æ¯”èµ?Suzhou Yinfeng Dream Art Piano competition 7:00 17:30 Function Room 1 Meeting Theater 80 80 80 - Prospect Nico Lin - -
è‹å·žéŸ³ä¸ºæ¢¦ç»„ç»‡é’¢ç´æ¯”èµ?Suzhou Yinfeng Dream Art Piano competition 18:00 21:00 Function Room 2 Dinner Round Tables of 10 20 20 20 - Prospect Nico Lin - -
Event Start Date: 01/07/2026 (3 records)
è¥¿é—¨å­æœºåºŠå®¢æˆ·æ—¥ Siemens Meeting 5:00 23:00 Grand Ballroom Setup Existing Setup 10 10 10 - Prospect Cecily Hong - -
æ–°ä¸œæ–¹æ•™è‚²å±• - Suzhou New Oriental School Meeting 9:00 18:00 Grand Ballroom Meeting Classroom 300 300 ### - Prospect Lily Xie - -
è¥¿é—¨å­æœºåºŠå®¢æˆ·æ—¥ Siemens Meeting 8:00 22:00 TBA Meeting Classroom 600 550 ### - Prospect Cecily Hong - -
Event Start Date: 02/07/2026 (7 records)
åŽæ˜Ÿå…‰ç”µæ¨å…ˆç”ŸåŒå­¦ä¼šæ™šå®´ Star Optoelectronic Dinner 16:15 21:00 Function Room 2+3+4 Dinner Round Tables of 10 80 70 80 - Prospect Lily Xie - -
è¥¿é—¨å­æœºåºŠå®¢æˆ·æ—¥ Siemens Meeting 8:00 22:00 Grand Ballroom Meeting - 200 180 ### - Prospect Cecily Hong - -
ä¸Šæµ·ç»´åº¦ --IT SHA WeiDu--IT 8:00 22:00 Grand Ballroom 2+3 Meeting Existing Setup 250 230 ### - Prospect Cecily Hong - -
Event Start Date: 03/07/2026 (2 records)
é™ˆå…ˆç”Ÿå®¶å‡å­¦å®?Thanks Dinner of Mr.Chen 15:00 21:00 Grand Ballroom 1 Dinner Round Tables of 10 70 70 70 - Prospect Luisa Liu Luisa Liu Luisa Liu
é™ˆå…ˆç”Ÿå®¶å‡å­¦å®?Thanks Dinner of Mr.Chen 13:00 21:00 VIP Room Room Hold Existing Setup 20 20 20 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 04/07/2026 (2 records)
ä¸Šæµ·ç»´åº¦ --IT SHA WeiDu--IT 8:00 18:00 Grand Ballroom Meeting Existing Setup 250 230 ### - Prospect Cecily Hong - -
Event Start Date: 05/07/2026 (2 records)
è¯ºå’Œè¯ºå¾·ä¼šè®® Novo Nordisk Meeting 8:00 22:00 Grand Ballroom Meeting Classroom 300 270 ### - Prospect Cecily Hong - -
è¯ºå’Œè¯ºå¾·ä¼šè®® Novo Nordisk Meeting 8:00 18:00 Function Room 5+6 Meeting Fish Bone 40 35 40 - Prospect Cecily Hong - -
è¯ºå’Œè¯ºå¾·ä¼šè®® Novo Nordisk Meeting 8:00 18:00 Function Room 1 Meeting Fish Bone 40 35 40 - Prospect Cecily Hong - -
è¯ºå’Œè¯ºå¾·ä¼šè®® Novo Nordisk Meeting 8:00 18:00 Function Room 2+3+4 Meeting Fish Bone 40 35 40 - Prospect Cecily Hong - -
Event Start Date: 09/07/2026 (1 record)
èµ›é»˜é£žä¼šè®?Thermo Fisher Meeting 7:00 18:00 Function Room 2+3+4 Meeting Classroom 63 63 63 - Prospect Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 10/07/2026 (2 records)
æŽå…ˆç”Ÿè®¢å©šåˆå®?Mr.Li's Engagement Lunch 7:00 15:00 Grand Ballroom 1 Lunch Round Tables of 10 100 90 ### - Definite Luisa Liu Nico Lin Nico Lin
Event Start Date: 11/07/2026 (2 records)
æ¸£æ‰“é“¶è¡Œä¼šè®® Standard Chartered Bank Meeting 7:00 17:00 Grand Ballroom 3 Meeting Classroom 72 63 63 - Definite Luisa Liu Luisa Liu Luisa Liu
æ¸£æ‰“é“¶è¡Œä¼šè®® Standard Chartered Bank Meeting 15:00 15:30 Grand Ballroom Foyer Break PM Coffee Station 40 40 40 - Definite Luisa Liu Luisa Liu Luisa Liu
æ¸£æ‰“é“¶è¡Œä¼šè®® Standard Chartered Bank Meeting 7:00 11:00 Grand Ballroom 3 Setup Classroom 2 2 2 - Definite Luisa Liu Luisa Liu Luisa Liu
Event Start Date: 12/07/2026 (3 records)
æ²ˆä¹¦è®°å®¶çš„å®å®å®´ The Baby Lunch of Mr. Shen 8:00 14:00 Grand Ballroom 1+2 Lunch Round Tables of 10 180 180 ### - Definite Elaine He - -
æ²ˆä¹¦è®°å®¶çš„å®å®å®´ The Baby Lunch of Mr. Shen 8:00 14:00 VIP Room Room Hold Existing Setup 15 12 15 - Definite Elaine He - -
æ²ˆä¹¦è®°å®¶çš„å®å®å®´ The Baby Lunch of Mr. Shen 8:00 14:00 Rest Room/Bride Room Room Hold No Set Up Required 8 6 8 - Definite Elaine He - -
Event Start Date: 13/07/2026 (1 record)
ä¸­ç§‘çœ‹ç‚¹æ´»åŠ¨ Zhongke Kandian Meeting 12:00 17:30 Grand Ballroom 3 Meeting Classroom 105 105 ### - Prospect Nico Lin - -
ä¸­ç§‘çœ‹ç‚¹æ´»åŠ¨ Zhongke Kandian Meeting 11:00 17:30 Rest Room/Bride Room Setup Existing Setup 10 10 10 - Prospect Nico Lin - -
Event Start Date: 14/07/2026 (1 record)
è‹å·žäº‘æ…§å®¶åº­å’¨è¯¢ Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
è‹å·žäº‘æ…§å®¶åº­å’¨è¯¢ Suzhou Yun Hui Meeting 8:00 22:00 Function Room 6 Meeting Fish Bone 36 36 36 - Prospect Luisa Liu Luisa Liu Luisa Liu
"""

# Step 1: Parse
date_blocks = re.split(r'Event Start Date: ', RAW_TEXT)
event_blocks = []
for block in date_blocks:
    m = re.match(r'(\d{2}/\d{2}/\d{4}) \((\d+) records\)\n', block.strip())
    if m:
        day, month, year = m.group(1).split('/')
        iso_date = f"{year}-{month}-{day}"
        content = block[m.end():].strip()
        event_blocks.append((iso_date, int(m.group(2)), content))

print(f"Found {len(event_blocks)} date blocks")

# Parse events
all_events = []
rooms_pattern = r'(Grand Ballroom(?:\s+\d[\d\+]*)?|Function Room(?:\s+\d[\d\+\.,]*)?|Italian Restera(?:nt|urant)|Boardroom|VIP Room|Rest Room/Bride Room|Business Center|All Day Dining|OPEN|Bar Beer Society|BACIO|Function Room Foyer|Grand Ballroom Foyer|TBA)'
setup_patterns = r'(Lunch Buffet|Wedding Dinner|Meeting|Lunch|Dinner|Dinner Round Tables|Setup|Break|Room Hold|Boxed Dinner|Coffee Station|Activities/Recreation|Special Setup|Reception)'
owners_list = ["Elaine He", "Luisa Liu", "Lily Xie", "Nico Lin", "Cecily Hong", "Catherine Xu"]
event_name_pattern = r'(The (Wedding|Lunch|Dinner|Thanks|Birthday|Baby|dinner|Dinner|Lunch)\s+of\s+[\w\s.]+|Meeting|[\w\s]+Meeting|[\w\s]+Group)'

for iso_date, count, content in event_blocks:
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line or line.startswith('Event Start Date:') or line.startswith('Grand Totals'):
            continue
        
        status = 'Definite'
        if 'Tentative' in line: status = 'Tentative'
        elif 'Prospect' in line: status = 'Prospect'
        
        time_match = re.findall(r'(\d{1,2}:\d{2})\s+(\d{1,2}:\d{2})', line)
        start_time = time_match[0][0] + ':00' if time_match else ''
        end_time = time_match[0][1] + ':00' if len(time_match) > 0 else ''
        
        room_match = re.search(rooms_pattern, line)
        setup_match = re.search(setup_patterns, line)
        
        eng_match = re.search(event_name_pattern, line)
        eng_name = eng_match.group(0) if eng_match else ''
        
        # Chinese name
        chn_name = ''
        if eng_match:
            idx = line.find(eng_match.group(0))
            if idx > 0:
                potential_chn = line[:idx].strip()
                chn_chars = re.findall(r'[\u4e00-\u9fffã€Šã€‹â€”\-]+', potential_chn)
                chn_name = ' '.join(chn_chars) if chn_chars else ''
        
        # BEO number
        beo_num = ''
        beo_num_match = re.search(r'(\d{4})[-\s]*(?:BEO|Definite)', line)
        if beo_num_match: beo_num = beo_num_match.group(1)
        
        # Owner
        owner = ''
        for o in owners_list:
            if o in line: owner = o; break
        
        if chn_name or eng_name:
            all_events.append({
                'date': iso_date, 'chinese_name': chn_name, 'english_name': eng_name,
                'start': start_time, 'end': end_time,
                'room': room_match.group(0) if room_match else '',
                'setup': setup_match.group(0) if setup_match else '',
                'status': status, 'owner': owner, 'beo': beo_num
            })

print(f"Parsed {len(all_events)} events")

# Step 2: Import into FIN graph
shutil.copy(FIN_GRAPH, FIN_GRAPH.with_suffix('.pre_beo_20260606.json'))

with open(FIN_GRAPH, "r", encoding="utf-8") as f:
    fin = json.load(f)

def exists_in(entity_list, eid):
    return any(e.get('id') == eid for e in entity_list)

# Create report entity
REPORT_ID = "BEO_20260606"
if not exists_in(fin['entities'], REPORT_ID):
    fin['entities'].append({
        "id": REPORT_ID,
        "name": "BEO Daily Event 6.6-7.30",
        "type": "fin_report",
        "date": "2026-06-06",
        "properties": {
            "report_label": "BEO_SZVTV",
            "hotel": "Hotel-A",
            "report_date": "2026-06-06",
            "filter_from": "2026-06-06",
            "filter_to": "2026-07-30",
            "total_events": len(all_events),
            "generated_by": "Elaine He",
            "source_file": "6.6-7.30Report.pdf",
            "imported_at": "2026-06-06"
        }
    })

# Link to FIN_YEAR_2026
FIN_YEAR = "FIN_YEAR_2026"
rel_key = f"REL_{REPORT_ID}_belongs_to_{FIN_YEAR}"
if not any(r.get('id') == rel_key for r in fin['relationships']):
    fin['relationships'].append({
        "source_id": REPORT_ID, "target_id": FIN_YEAR,
        "relation": "BELONGS_TO", "id": rel_key,
        "type": "BELONGS_TO", "source": REPORT_ID, "target": FIN_YEAR
    })

# Add events
event_count_by_status = Counter(e['status'] for e in all_events)
new_count = 0

for e in all_events:
    safe_date = e['date'].replace('-', '')
    short_name = (e['english_name'][:20] if e['english_name'] else e['chinese_name'][:10]).replace('/', '_').replace(' ', '_')
    event_id = f"BEO_{safe_date}_{short_name}"
    
    if exists_in(fin['entities'], event_id):
        continue
    
    fin['entities'].append({
        "id": event_id,
        "name": f"[BEO] {e['date']} {e['chinese_name']} {e['english_name'][:40]}",
        "type": "beo_event",
        "date": e['date'],
        "properties": {
            "date": e['date'], "event_date": e['date'],
            "chinese_name": e['chinese_name'], "english_name": e['english_name'],
            "start_time": e['start'], "end_time": e['end'],
            "room": e['room'], "setup": e['setup'],
            "status": e['status'], "owner": e['owner'], "beo_number": e['beo']
        }
    })
    new_count += 1
    
    event_rel = f"REL_{event_id}_belongs_to_{REPORT_ID}"
    if not any(r.get('id') == event_rel for r in fin['relationships']):
        fin['relationships'].append({
            "source_id": event_id, "target_id": REPORT_ID,
            "relation": "BELONGS_TO", "id": event_rel,
            "type": "BELONGS_TO", "source": event_id, "target": REPORT_ID
        })

# Update meta
fin['meta']['version'] = fin['meta'].get('version', '') + ' + BEO_6.6-7.30'
fin['meta']['updated'] = '2026-06-06 09:15'
fin['meta']['last_batch_import'] = 'BEO 6.6-7.30 Report'

with open(FIN_GRAPH, "w", encoding="utf-8") as f:
    json.dump(fin, f, ensure_ascii=False, indent=2)

print(f"\nâœ?Import complete!")
print(f"  New events added: {new_count}")
print(f"  Total FIN entities: {len(fin['entities'])}")
print(f"  Status breakdown: {dict(event_count_by_status)}")
print(f"  Date range: {event_blocks[0][0]} to {event_blocks[-1][0]}")
print(f"  Backup saved: fin_graph.pre_beo_20260606.json")
